version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: 'bitnami/opencart:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 80:80
      - 443:443
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
  jenkins:
    image: jenkins-docker
    build: .
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - default
    volumes:
      - "./config/browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid_video:/opt/selenoid/video"
      - "./selenoid_logs:/opt/selenoid/logs"
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    ports:
      - "8082:8080"
    command: ["--selenoid", "http://selenoid:4444"]
volumes:
  jenkins-home:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local